### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by ugintl** [peterpeterparker/tietracker#136]
What tools to I need to install it?

Is indexedDB only option?

**Comment by peterpeterparker** [comment]
> What tools to I need to install it?

What do you mean?!

The app is available as a PWA or in the App and Play stores.
If you wish to run it locally, ensure you have NodeJS installed locally and proceed as displayed in the [README](https://github.com/peterpeterparker/tietracker#development).

> Is indexedDB only option?

It works only with indexeddb

**Comment by ugintl** [comment]
@peterpeterparker WHat version of nodejs?

Which files are used to save the data?

**Comment by peterpeterparker** [comment]
> WHat version of nodejs?

TLS. Currently npm v6 but probably soon v7

> Which files are used to save the data?

Again, not sure what you mean here, there are no files

**Comment by ugintl** [comment]
@peterpeterparker It will be saving data some where. This is what I mean.

**Comment by peterpeterparker** [comment]
In IndexedDB.

**Comment by peterpeterparker** [comment]
Npm v7 has just been merged in main branch.

I guess this question is now solved therefore I close the issue.
