### ISSUE TITLE
Unable to delete older time periods

### ISSUE THREAD

**Issue by Desperationis** [peterpeterparker/tietracker#152]
You are unable to delete older time periods than what has happened in one day. I accidentally left Tie Tracker running over night, and I was greated with a 16+ hour time period this morning that is reported as happening yesterday. I tried inputting a negative time period to counteract it, but it does not report it to the invoice tab. 

Not that inconvenient as I can always subtract it later, but it would be nice to be able to delete them. I'm not too sure where the data is specifically saved so I might be able to delete it there.

**Comment by peterpeterparker** [comment]
I think - hope - this should be possible. Have you try selecting previous date? You did not find the entry there?

<img width="1510" alt="Capture d’écran 2022-07-12 à 21 59 38" src="https://user-images.githubusercontent.com/16886711/178583472-81f8012e-f898-4db2-911a-25c1f85dac39.png">

**Comment by Desperationis** [comment]
I feel so dumb for completely forgetting about that button. Thanks so much!

**Comment by peterpeterparker** [comment]
The button isn't that obvious I have to say but did no knew where to place it elsewhere. Happy to hear it worked out!
