### ISSUE TITLE
Minimum Time seems to be capped

### ISSUE THREAD

**Issue by preetjdp** [peterpeterparker/tietracker#68]
Hi trying out the app and there seems to be a minimum time cap of 5 minutes, i.e., even if I use the timer of 10 seconds it is recorded as 5 Minutes.
Attached an image (Used the timer for only 10 seconds and recorded as 5 minutes).

![image](https://user-images.githubusercontent.com/27439197/76636217-b07cd380-656e-11ea-8577-efb71fc27223.png)

**Comment by peterpeterparker** [comment]
Thx you for opening an issue, that's actually feature or it's per design ;)

In your settings, you can defined if you want your recorded time being round to 1, 5 or 15 min.

But, if you enter an entry manually or modify a recorded entry, then there is no rounding (only when you start/stop with tracking).

<img width="623" alt="Capture d’écran 2020-03-13 à 21 29 02" src="https://user-images.githubusercontent.com/16886711/76657329-e2dc0000-6571-11ea-9c06-db1bfc092bbe.png">
