### ISSUE TITLE
update entry change the "From" date to exactly 1 day before

### ISSUE THREAD

**Issue by peterpeterparker** [peterpeterparker/tietracker#87]
as discussed in #86 it seems that such issue might be happening on iOS. 

is anyone facing it too?  only iOS  or Android too? is there a reproducible path to face the issue (I did not face it on my phone)? 

any inputs appreciated

**Comment by andrewdmaclean** [comment]
@peterpeterparker thanks for making this a seperate issue.

I am wondering if with the changes required for #86 it might resolve itself?

**Comment by peterpeterparker** [comment]
@andrewdmaclean I don't think so unfortunately. next time I use my test iPhone will try to check if I can reproduce the issue.

**Comment by andrewdmaclean** [comment]
@peterpeterparker I just tried out the new template feature on https://tietracker.com and discovered that the issue exists there too.

I recorded a screen capture so you can see my workflow

![1](https://user-images.githubusercontent.com/26526271/98171328-6c936180-1ea4-11eb-8175-a4edb48773d2.gif)
![2](https://user-images.githubusercontent.com/26526271/98171333-6dc48e80-1ea4-11eb-9d3d-2d4e073ba3e0.gif)
![3](https://user-images.githubusercontent.com/26526271/98171339-6f8e5200-1ea4-11eb-9e56-7df3dc8bbc47.gif)
![4](https://user-images.githubusercontent.com/26526271/98171343-70bf7f00-1ea4-11eb-91f3-a4619582bd06.gif)

**Comment by peterpeterparker** [comment]
crazy, how is that even possible 🤔

tried the exact same behavior on Chrome and Firefox on Mac, did not face the problem.

Which browser and OS did you use to reproduce the error?

Either something like that or a timezone issue? (should not I used a lib to handle dates)

**Comment by andrewdmaclean** [comment]
Using Firefox 82.0.2 (64-bit) on Windows 10 Home Version 10.0.19041 Build 19041 and just tried on my Macbook Air and discovered the same issue, so it might indeed be the timezone.

**Comment by andrewdmaclean** [comment]
@peterpeterparker Yup! Just changed my timezone to UTC +1 and everything is working 👍

**Comment by peterpeterparker** [comment]
Dammed timezone 😜

Thx for inspecting the issue. A bit late for today, I will give it a try in the next days. I keep you posted.

**Comment by andrewdmaclean** [comment]
@peterpeterparker No worries or rush at all 😄 

I am really enjoying the project and even more to using it to its full potential 👌

**Comment by peterpeterparker** [comment]
@andrewdmaclean I  am sorry, I tested 4 different timezones and could not reproduce the issue  🤷‍♂️

I need your hand to debug if you have got a bit more time. Can you track this new staging url https://tie-tracker-staging.web.app/ in an incognito browser, create a  project and  try to reproduce the error  and then send me the output  the chrome debugger

maybe, hopefully, I'll  notice a difference in comparison to what works for me

thx in  advance!

<img width="1161" alt="Capture d’écran 2020-11-05 à 22 33 12" src="https://user-images.githubusercontent.com/16886711/98298974-3561a500-1fb7-11eb-8fba-8f3fdb895bf9.png">

**Comment by andrewdmaclean** [comment]
![image](https://user-images.githubusercontent.com/26526271/98302609-91093f80-1f71-11eb-8452-5f4bc23e1814.png)

@peterpeterparker here you are :)
```
Content is cached for offline use. serviceWorker.ts:93:24
1 task-in-progress {"id":"05a87bd3-851d-47b1-b459-ff6f3690dd5b","data":{"from":1604614546926,"client_id":"4b51fbec-6976-445e-be6b-1978e63a1a7d","project_id":"b25c9753-423d-4a4a-8116-0c0d77bd11c7","created_at":1604614546926,"updated_at":1604614546926,"project":{"name":"test","rate":{"hourly":10,"vat":false}},"client":{"name":"Test","color":"#8ED1FC"},"invoice":{"status":"open"},"description":"Development"}} tasks.service.ts:41:16
2 tasks-2020-11-05 [{"id":"05a87bd3-851d-47b1-b459-ff6f3690dd5b","data":{"from":1604614500000,"client_id":"4b51fbec-6976-445e-be6b-1978e63a1a7d","project_id":"b25c9753-423d-4a4a-8116-0c0d77bd11c7","created_at":1604614546926,"updated_at":1604614552242,"invoice":{"status":"open"},"description":"Development","to":1604614800000}}] tasks.service.ts:246:16
3 invoices ["2020-11-05"] tasks.service.ts:214:14
```

### Here is my timezone information
---
Pacific Standard Time
Time zone in Vancouver, BC (GMT-8)
Thursday, November 5, 2020, 2:18 p.m.

**Comment by peterpeterparker** [comment]
@andrewdmaclean awesome, thx for the info, I can reproduce the error!

I did not find the solution yet, indeed it's a timezone issue,  dates are tricky. I'll try to work on it this weekend.

**Comment by peterpeterparker** [comment]
Yes! I was able to solve this issue I think :)

I have deployed the fix on staging and on tietracker.com. I'll also take care to ship a new version to the App Store and Google Play asap. 

Let me know if you still notice this or another issue @andrewdmaclean and thanks a lot for your help and support 🙏

**Comment by andrewdmaclean** [comment]
@peterpeterparker I just checked and everything seems to be working 😀

If you have some time, I would love to know how you develop this way, with the web app to iOS and Android apps?

**Comment by peterpeterparker** [comment]
Awesome @andrewdmaclean, thank you for double checking!

I am using [Ionic](https://ionicframework.com/) and [Capacitor](https://capacitorjs.com/) to develop this  application. Using these am I able to have the same codebase and to deploy the same app as a Web / Progressive Web Apps and in both App Store in Google Play.

Let me know if you have more questions.
