### ISSUE TITLE
How is the timer getting maintained?

### ISSUE THREAD

**Issue by rhaegar453** [peterpeterparker/tietracker#92]
Are you storing the timer on the client side or storing it on the server?

**Comment by peterpeterparker** [comment]
there is no server, currently the app works 100%  offline.

why?

**Comment by rhaegar453** [comment]
I'm just trying to implement a similar functionality in my app. May I know how you're storing the timer on the client side?

**Comment by rhaegar453** [comment]
I want the timer to continue running even if I close and visit the tab again?

**Comment by peterpeterparker** [comment]
Spontaneously I would say that you should preserved a state somewhere (client side, user data etc.) you would be able to read to detect if a timer is in progress or not, or maybe even save a state in the timer itself (started - finished). Then when there is a refresh, you read the state and according it's value, you resume.

As I use idb, I save in it a "task-in-progress". When this value is set, means something is running, if empty, then nothing to restat.

Hope this helps a bit, good luck with your project!
